name: Create Zip
on: 
  push:
    branches:
      -master

jobs:
  create_zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Zip File
        run:
          zip -r my-repo.zip
      - name: Create Zip File
        with:
          name: my-repo.zip
          path: my-repo.zip
