name: Create and Upload Zip File
on:
  push:
    branches:
      - master
jobs:
  create_and_upload_zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Zip File
        run: |
          zip -r -FS my_repo.zip .
      - name: Upload Zip File
        uses: actions/upload-artifact@v3
        with:
          name: my_repo.zip
          path: my_repo.zip
